# Generated by Django 6.0.6 on 2026-06-23 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior'), ('pro', 'Pro')], default='junior', max_length=20)),
                ('base_price', models.PositiveIntegerField(default=0)),
                ('average_delivery_hours', models.PositiveIntegerField(default=24)),
                ('rating_average', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('completed_orders_count', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('accepts_direct_requests', models.BooleanField(default=True)),
                ('accepts_public_requests', models.BooleanField(default=True)),
                ('accepts_sample_challenges', models.BooleanField(default=True)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills', models.ManyToManyField(blank=True, related_name='editor_profiles', to='catalog.editstyle')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='editor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Editor profile',
                'verbose_name_plural': 'Editor profiles',
                'ordering': ['-rating_average', '-completed_orders_count', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='EditorPortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('before_image', models.ImageField(blank=True, null=True, upload_to='editor_portfolio/before/')),
                ('after_image', models.ImageField(blank=True, null=True, upload_to='editor_portfolio/after/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_items', to='catalog.editstyle')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='accounts.editorprofile')),
            ],
            options={
                'verbose_name': 'Editor portfolio item',
                'verbose_name_plural': 'Editor portfolio items',
                'ordering': ['editor', 'sort_order', '-created_at'],
            },
        ),
    ]
