# Generated by Django 6.0.6 on 2026-06-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_editorprofile_editorportfolioitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorprofile',
            name='rating_average',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
