# Generated by Django 6.0.6 on 2026-07-23 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_portfoliocomment_portfoliocommentreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorportfolioitem',
            name='review_note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='editorportfolioitem',
            name='review_status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending', 'در انتظار بررسی'), ('approved', 'تأییدشده'), ('rejected', 'ردشده')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='editorportfolioitem',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='editorportfolioitem',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_portfolio_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
