# Generated by Django 6.0.6 on 2026-06-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_at', '-id')},
        ),
    ]
