# Generated by Django 6.0.6 on 2026-06-23 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_closed_at_order_paid_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('order_submitted', 'Order Submitted'), ('review_started', 'Review Started'), ('editor_assigned', 'Editor Assigned'), ('work_started', 'Work Started'), ('delivery_uploaded', 'Delivery Uploaded'), ('supervisor_approved', 'Supervisor Approved'), ('supervisor_revision_requested', 'Supervisor Revision Requested'), ('editor_revision_started', 'Editor Revision Started'), ('client_approved', 'Client Approved'), ('client_revision_requested', 'Client Revision Requested'), ('supervisor_accepted_client_revision', 'Supervisor Accepted Client Revision'), ('supervisor_rejected_client_revision', 'Supervisor Rejected Client Revision'), ('comment_created', 'Comment Created'), ('comment_updated', 'Comment Updated'), ('comment_deleted', 'Comment Deleted'), ('rating_created', 'Rating Created'), ('rating_updated', 'Rating Updated'), ('settlement_started', 'Settlement Started'), ('payment_recorded', 'Payment Recorded'), ('order_closed', 'Order Closed')], max_length=64)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='orders.order')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
