# Generated by Django 6.0.6 on 2026-06-23 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderactivitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_review', 'In Review'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('client_review', 'Client Review'), ('revision_required', 'Revision Required'), ('client_revision_requested', 'Client Revision Requested'), ('completed', 'Completed'), ('settlement_pending', 'Settlement Pending'), ('paid', 'Paid'), ('closed', 'Closed')], default='draft', max_length=32),
        ),
        migrations.AlterField(
            model_name='ordercomment',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordercomment',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderrating',
            name='rated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderrevision',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='orderrating',
            constraint=models.UniqueConstraint(fields=('order', 'source'), name='unique_order_rating_per_source'),
        ),
    ]
