# Generated by Django 6.0.6 on 2026-06-23 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status_alter_ordercomment_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='orders.ordercomment'),
        ),
    ]
