# Generated by Django 6.0.6 on 2026-06-23 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_ordercomment_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercomment',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordercomment',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_order_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderactivitylog',
            name='activity_type',
            field=models.CharField(choices=[('order_submitted', 'Order Submitted'), ('review_started', 'Review Started'), ('editor_assigned', 'Editor Assigned'), ('work_started', 'Work Started'), ('delivery_uploaded', 'Delivery Uploaded'), ('supervisor_approved', 'Supervisor Approved'), ('supervisor_revision_requested', 'Supervisor Revision Requested'), ('editor_revision_started', 'Editor Revision Started'), ('client_approved', 'Client Approved'), ('client_revision_requested', 'Client Revision Requested'), ('supervisor_accepted_client_revision', 'Supervisor Accepted Client Revision'), ('supervisor_rejected_client_revision', 'Supervisor Rejected Client Revision'), ('comment_created', 'Comment Created'), ('comment_updated', 'Comment Updated'), ('comment_deleted', 'Comment Deleted'), ('rating_created', 'Rating Created'), ('rating_updated', 'Rating Updated'), ('settlement_started', 'Settlement Started'), ('payment_recorded', 'Payment Recorded'), ('order_closed', 'Order Closed'), ('comment_resolved', 'Comment resolved'), ('comment_unresolved', 'Comment unresolved')], max_length=64),
        ),
    ]
