# Generated by Django 6.0.6 on 2026-06-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_ordercomment_resolved_at_ordercomment_resolved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercomment',
            name='annotation_color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ordercomment',
            name='annotation_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ordercomment',
            name='annotation_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='ordercomment',
            name='annotation_type',
            field=models.CharField(choices=[('none', 'None'), ('point', 'Point'), ('rectangle', 'Rectangle'), ('circle', 'Circle'), ('arrow', 'Arrow'), ('freehand', 'Freehand')], default='none', max_length=20),
        ),
    ]
