# Generated by Django 6.0.6 on 2026-06-27 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_ordernotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdelivery',
            name='publication_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='publication_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='publication_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_delivery_publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='publication_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='publication_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_delivery_publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderdelivery',
            name='publication_status',
            field=models.CharField(choices=[('private', 'Private'), ('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='private', max_length=32),
        ),
    ]
