# Generated by Django 6.0.6 on 2026-06-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_orderdelivery_publication_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='agreed_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Final agreed order price.', max_digits=14),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Site commission amount for this order.', max_digits=14),
        ),
        migrations.AddField(
            model_name='order',
            name='editor_earning',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Editor earning after commission.', max_digits=14),
        ),
        migrations.AddField(
            model_name='order',
            name='escrow_held',
            field=models.BooleanField(default=False, help_text='Whether the order amount is currently held in escrow.'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_settled',
            field=models.BooleanField(default=False, help_text='Whether final financial settlement has been completed.'),
        ),
        migrations.AddField(
            model_name='orderactivitylog',
            name='tx_ref',
            field=models.CharField(blank=True, help_text='Related transaction reference.', max_length=100),
        ),
    ]
