# Generated by Django 6.0.6 on 2026-07-04 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_settlement_payment_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_percent_per_day', models.DecimalField(decimal_places=2, default=2.0, help_text='Penalty percentage per day late (e.g. 2.00 = 2% per day)', max_digits=5)),
                ('max_penalty_percent', models.DecimalField(decimal_places=2, default=20.0, help_text='Maximum total penalty percentage (e.g. 20 = max 20% of order)', max_digits=5)),
                ('grace_period_hours', models.PositiveIntegerField(default=2, help_text='Hours of grace period before penalty starts')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SLA Configuration',
                'verbose_name_plural': 'SLA Configurations',
            },
        ),
        migrations.CreateModel(
            name='DeliveryPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_type', models.CharField(choices=[('late_delivery', 'Late delivery'), ('quality_issue', 'Quality issue'), ('manual', 'Manual penalty')], default='late_delivery', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('waived', 'Waived'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('order_amount', models.DecimalField(decimal_places=0, help_text='Original order amount (agreed_price)', max_digits=14)),
                ('penalty_amount', models.DecimalField(decimal_places=0, help_text='Penalty amount deducted from editor', max_digits=14)),
                ('penalty_percent', models.DecimalField(decimal_places=2, default=0, help_text='Penalty as percentage of order amount', max_digits=5)),
                ('deadline', models.DateTimeField(help_text='Original order deadline')),
                ('delivered_at', models.DateTimeField(blank=True, help_text='When order was actually delivered', null=True)),
                ('days_late', models.PositiveIntegerField(default=0, help_text='Number of days late')),
                ('reason', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('waived_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties_applied', to=settings.AUTH_USER_MODEL)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties_received', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='orders.order')),
                ('waived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties_waived', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Penalty',
                'verbose_name_plural': 'Delivery Penalties',
                'ordering': ('-created_at',),
            },
        ),
    ]
