# Generated by Django 6.0.6 on 2026-07-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_workflowdeadline'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workflowdeadline',
            new_name='orders_work_status_28c479_idx',
            old_name='orders_work_status_1dd769_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowdeadline',
            new_name='orders_work_order_i_175e38_idx',
            old_name='orders_work_order_i_b3e739_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowdeadline',
            new_name='orders_work_project_f0c29b_idx',
            old_name='orders_work_project_0fb75a_idx',
        ),
    ]
