# Generated by Django 6.0.6 on 2026-06-23 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_editorprofile_editorportfolioitem'),
        ('catalog', '0001_initial'),
        ('orders', '0012_ordernotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('direct_editor', 'Direct editor'), ('public_quote', 'Public quote'), ('sample_challenge', 'Sample challenge'), ('managed_order', 'Managed order')], default='managed_order', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('open_for_quotes', 'Open for quotes'), ('open_for_samples', 'Open for samples'), ('waiting_for_editor', 'Waiting for editor'), ('under_review', 'Under review'), ('editor_selected', 'Editor selected'), ('converted_to_order', 'Converted to order'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='draft', max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('budget_min', models.PositiveIntegerField(default=0)),
                ('budget_max', models.PositiveIntegerField(default=0)),
                ('preferred_deadline', models.DateTimeField(blank=True, null=True)),
                ('image_count', models.PositiveIntegerField(default=0)),
                ('client_note', models.TextField(blank=True)),
                ('support_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_requests', to=settings.AUTH_USER_MODEL)),
                ('converted_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_project_request', to='orders.order')),
                ('edit_style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_requests', to='catalog.editstyle')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_requests', to='catalog.editpackage')),
                ('target_editor', models.ForeignKey(blank=True, help_text='Used for direct editor requests.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_project_requests', to='accounts.editorprofile')),
            ],
            options={
                'verbose_name': 'Project request',
                'verbose_name_plural': 'Project requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRequestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_requests/originals/')),
                ('caption', models.CharField(blank=True, max_length=180)),
                ('is_sample_image', models.BooleanField(default=False, help_text='Used for sample challenge requests.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.projectrequest')),
            ],
            options={
                'verbose_name': 'Project request image',
                'verbose_name_plural': 'Project request images',
                'ordering': ['sort_order', 'uploaded_at'],
            },
        ),
    ]
