# Generated by Django 6.0.6 on 2026-06-23 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_editorprofile_editorportfolioitem'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('accepted_by_client', 'Accepted by client'), ('declined_by_editor', 'Declined by editor'), ('rejected_by_client', 'Rejected by client'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=30)),
                ('proposed_price', models.PositiveIntegerField(default=0)),
                ('editor_fee', models.PositiveIntegerField(default=0, help_text='Internal editor fee or requested wage.')),
                ('estimated_delivery_hours', models.PositiveIntegerField(default=24)),
                ('editor_note', models.TextField(blank=True)),
                ('client_note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_proposals', to='accounts.editorprofile')),
                ('project_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='projects.projectrequest')),
            ],
            options={
                'verbose_name': 'Project proposal',
                'verbose_name_plural': 'Project proposals',
                'ordering': ['-submitted_at'],
                'constraints': [models.UniqueConstraint(fields=('project_request', 'editor'), name='unique_project_proposal_per_editor')],
            },
        ),
    ]
