# Generated by Django 6.0.6 on 2026-06-23 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectproposal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectproposal',
            name='is_visible_to_client',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_project_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='sample_file',
            field=models.FileField(blank=True, null=True, upload_to='project_proposals/samples/'),
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='sample_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='supervisor_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectproposal',
            name='supervisor_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Score from 1 to 10.', null=True),
        ),
        migrations.AlterField(
            model_name='projectproposal',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('approved', 'Approved'), ('rejected_by_supervisor', 'Rejected by supervisor'), ('accepted_by_client', 'Accepted by client'), ('declined_by_editor', 'Declined by editor'), ('rejected_by_client', 'Rejected by client'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=30),
        ),
    ]
