# Generated by Django 6.0.6 on 2026-06-27 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectproposal_is_visible_to_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequestActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('image_uploaded', 'Image uploaded'), ('direct_proposal_submitted', 'Direct proposal submitted'), ('direct_declined', 'Direct declined'), ('public_proposal_submitted', 'Public proposal submitted'), ('sample_proposal_submitted', 'Sample proposal submitted'), ('sample_proposal_reviewed', 'Sample proposal reviewed'), ('proposal_selected', 'Proposal selected'), ('converted_to_order', 'Converted to order'), ('managed_assigned', 'Managed assigned')], max_length=64)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_request_activities', to=settings.AUTH_USER_MODEL)),
                ('project_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.projectrequest')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['project_request', '-created_at'], name='projects_pr_project_13fd55_idx'), models.Index(fields=['action'], name='projects_pr_action_2d4d6b_idx')],
            },
        ),
    ]
