# Generated by Django 6.0.6 on 2026-06-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projectrequestactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrequestactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('image_uploaded', 'Image uploaded'), ('direct_proposal_submitted', 'Direct proposal submitted'), ('direct_declined', 'Direct declined'), ('public_proposal_submitted', 'Public proposal submitted'), ('sample_proposal_submitted', 'Sample proposal submitted'), ('sample_reviewed', 'Sample reviewed'), ('proposal_selected', 'Proposal selected'), ('converted_to_order', 'Converted to order'), ('managed_assigned', 'Managed assigned')], max_length=80),
        ),
    ]
