# Generated by Django 6.0.6 on 2026-06-27 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projectrequestactivity_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectrequest',
            options={'ordering': ('-created_at', '-id'), 'verbose_name': 'Project request', 'verbose_name_plural': 'Project requests'},
        ),
    ]
