# Generated by Django 6.0.6 on 2026-07-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_projectrequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequestimage',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Automatically calculated based on request type and submission date.', null=True),
        ),
        migrations.AlterField(
            model_name='projectrequestactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('image_uploaded', 'Image uploaded'), ('direct_proposal_submitted', 'Direct proposal submitted'), ('direct_declined', 'Direct declined'), ('public_proposal_submitted', 'Public proposal submitted'), ('sample_proposal_submitted', 'Sample proposal submitted'), ('sample_reviewed', 'Sample reviewed'), ('proposal_selected', 'Proposal selected'), ('converted_to_order', 'Converted to order'), ('managed_assigned', 'Managed assigned'), ('expired', 'Request expired'), ('proposal_auto_rejected', 'Proposal auto-rejected')], max_length=80),
        ),
    ]
