# Generated by Django 6.0.6 on 2026-07-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectrequestimage_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrequestimage',
            name='expires_at',
        ),
        migrations.AlterField(
            model_name='projectrequest',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Automatically calculated based on request type and submission date.', null=True),
        ),
    ]
