# Generated by Django 6.0.6 on 2026-07-23 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0018_rename_orders_work_status_1dd769_idx_orders_work_status_28c479_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('normal', 'مشتری عادی'), ('studio', 'آتلیه\u200cدار'), ('studio_vip', 'آتلیه\u200cدار VIP')], max_length=30, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('priority_level', models.PositiveSmallIntegerField(default=0)),
                ('badge_title', models.CharField(blank=True, max_length=80)),
                ('badge_color', models.CharField(default='#9B85E8', max_length=20)),
                ('monthly_price', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('annual_price', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('advertising_enabled', models.BooleanField(default=False)),
                ('logo_enabled', models.BooleanField(default=False)),
                ('featured_listing_enabled', models.BooleanField(default=False)),
                ('is_purchasable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PerformanceCommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('min_rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('min_likes', models.PositiveIntegerField(default=0)),
                ('site_commission_percent', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('supervisor_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('expert_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-min_rating', '-min_likes', 'sort_order'),
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(blank=True, db_index=True, max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('landline', models.CharField(blank=True, max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('profile_completed', models.BooleanField(default=False)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_membership_profile', to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='customer_membership.customertier')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('active', 'فعال'), ('expired', 'منقضی'), ('cancelled', 'لغوشده')], db_index=True, default='pending', max_length=20)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('purchased_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('auto_renew', models.BooleanField(default=False)),
                ('payment_reference', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='customer_membership.customerprofile')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='customer_membership.customertier')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderPricingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=0, max_digits=14)),
                ('customer_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('customer_discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('final_price', models.DecimalField(decimal_places=0, max_digits=14)),
                ('site_commission_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('site_commission_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('supervisor_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('supervisor_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('expert_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('expert_amount', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('editor_earning', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('calculator_version', models.CharField(default='5.4.0', max_length=30)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership_pricing_snapshot', to='orders.order')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer_membership.performancecommissionrule')),
            ],
        ),
        migrations.CreateModel(
            name='StudioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio_name', models.CharField(max_length=180)),
                ('legal_name', models.CharField(blank=True, max_length=180)),
                ('manager_name', models.CharField(blank=True, max_length=150)),
                ('registration_number', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('secondary_phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=120)),
                ('activity_fields', models.TextField(blank=True)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='studios/logos/')),
                ('description', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('advertising_enabled', models.BooleanField(default=False)),
                ('featured_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studio', to='customer_membership.customerprofile')),
            ],
        ),
    ]
