'use client';
import {useEffect,useRef,useState} from 'react';
import {useRouter,useSearchParams} from 'next/navigation';
import {CheckCircle2,Loader2,ShieldAlert} from 'lucide-react';
import {authAPI} from '@/lib/api/auth';
import {getApiErrorMessage} from '@/lib/api/client';
import {useAuthStore} from '@/lib/stores/auth.store';
const DJANGO_BASE_URL=process.env.NEXT_PUBLIC_DJANGO_BASE_URL??'http://127.0.0.1:8000';
export default function AuthCallbackPage(){const router=useRouter();const params=useSearchParams();const setAuth=useAuthStore(s=>s.setAuth);const started=useRef(false);const [status,setStatus]=useState<'loading'|'success'|'error'>('loading');const [message,setMessage]=useState('در حال تکمیل ورود امن با گوگل...');
useEffect(()=>{if(started.current)return;started.current=true;const code=params.get('code');const oauthError=params.get('error');if(oauthError){setStatus('error');setMessage(oauthError==='account_disabled'?'این حساب غیرفعال شده است.':'ورود با گوگل لغو شد.');return;}if(!code){setStatus('error');setMessage('کد ورود دریافت نشد.');return;}void(async()=>{try{const result=await authAPI.exchangeSocialCode(code);setAuth(result.user,result.access,result.refresh);window.history.replaceState({},document.title,'/auth/callback');setStatus('success');setMessage('ورود موفق بود؛ در حال انتقال...');if(['admin','support','supervisor'].includes(result.user.role)){window.location.replace(new URL(result.redirect_to||'/panel/',DJANGO_BASE_URL).toString());}else{router.replace(result.redirect_to||'/dashboard');}}catch(error){setStatus('error');setMessage(getApiErrorMessage(error,'تکمیل ورود با گوگل ناموفق بود.'));}})();},[params,router,setAuth]);
return <main className="flex min-h-screen items-center justify-center bg-slate-50 px-4"><section className="w-full max-w-md rounded-3xl border bg-white p-8 text-center shadow-xl"><div className="mx-auto mb-5 flex h-16 w-16 items-center justify-center rounded-2xl bg-violet-50 text-violet-600">{status==='loading'&&<Loader2 className="animate-spin" size={32}/>} {status==='success'&&<CheckCircle2 size={32}/>} {status==='error'&&<ShieldAlert size={32}/>}</div><h1 className="text-xl font-bold">ورود به ریتاچر</h1><p className="mt-3 text-sm leading-7 text-slate-600">{message}</p>{status==='error'&&<button onClick={()=>router.replace('/login')} className="mt-6 w-full rounded-xl bg-violet-600 px-4 py-3 text-sm font-semibold text-white">بازگشت به صفحه ورود</button>}</section></main>}
