# Generated by Django 6.0.6 on 2026-07-22 10:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0018_rename_orders_work_status_1dd769_idx_orders_work_status_28c479_idx_and_more'),
        ('projects', '0008_remove_projectrequestimage_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('order', 'سفارش'), ('project', 'پروژه'), ('support', 'پشتیبانی'), ('internal', 'داخلی')], default='support', max_length=20)),
                ('is_archived', models.BooleanField(default=False)),
                ('last_message_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_panel_conversations', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panel_conversations', to='orders.order')),
                ('project_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panel_conversations', to='projects.projectrequest')),
            ],
            options={
                'ordering': ('-last_message_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('is_muted', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_links', to='operations_hub.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_participations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='panel_conversations', through='operations_hub.ConversationParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ManagedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='panel/files/%Y/%m/')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('input', 'فایل ورودی'), ('delivery', 'خروجی'), ('reference', 'مرجع'), ('contract', 'قرارداد'), ('general', 'عمومی')], default='general', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_private', models.BooleanField(default=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_files', to='orders.order')),
                ('project_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_files', to='projects.projectrequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_managed_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FileDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_download_logs', to=settings.AUTH_USER_MODEL)),
                ('managed_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_logs', to='operations_hub.managedfile')),
            ],
            options={
                'ordering': ('-downloaded_at',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'متن'), ('file', 'فایل'), ('system', 'سیستمی')], default='text', max_length=16)),
                ('body', models.TextField(blank=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='operations_hub.conversation')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='operations_hub.message')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panel_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='panel/chat/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='operations_hub.message')),
            ],
        ),
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('level', models.CharField(choices=[('info', 'اطلاعات'), ('warning', 'هشدار'), ('error', 'خطا'), ('security', 'امنیتی')], default='info', max_length=16)),
                ('method', models.CharField(blank=True, max_length=12)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('target_type', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['user', 'last_read_at'], name='operations__user_id_5009cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationparticipant',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='unique_conversation_participant'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['kind', 'is_archived'], name='operations__kind_f03ff6_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['last_message_at'], name='operations__last_me_44e9b5_idx'),
        ),
        migrations.AddIndex(
            model_name='managedfile',
            index=models.Index(fields=['order', 'category'], name='operations__order_i_be9aa0_idx'),
        ),
        migrations.AddIndex(
            model_name='managedfile',
            index=models.Index(fields=['project_request', 'category'], name='operations__project_67b651_idx'),
        ),
        migrations.AddIndex(
            model_name='managedfile',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='operations__uploade_617fcb_idx'),
        ),
        migrations.AddIndex(
            model_name='filedownloadlog',
            index=models.Index(fields=['managed_file', 'downloaded_at'], name='operations__managed_8b220f_idx'),
        ),
        migrations.AddIndex(
            model_name='filedownloadlog',
            index=models.Index(fields=['user', 'downloaded_at'], name='operations__user_id_e825f7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='operations__convers_5455c7_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='operations__sender__50af48_idx'),
        ),
        migrations.AddIndex(
            model_name='systemauditlog',
            index=models.Index(fields=['actor', 'created_at'], name='operations__actor_i_f03c93_idx'),
        ),
        migrations.AddIndex(
            model_name='systemauditlog',
            index=models.Index(fields=['action', 'created_at'], name='operations__action_506e53_idx'),
        ),
        migrations.AddIndex(
            model_name='systemauditlog',
            index=models.Index(fields=['level', 'created_at'], name='operations__level_a08be5_idx'),
        ),
    ]
