# Generated by Django 6.0.6 on 2026-06-28 12:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0013_orderdelivery_publication_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('manual', 'دستی (ادمین)')], default='zarinpal', max_length=20)),
                ('status', models.CharField(choices=[('created', 'ایجاد شده'), ('redirected', 'هدایت به درگاه'), ('success', 'پرداخت موفق'), ('failed', 'پرداخت ناموفق'), ('cancelled', 'لغو شده')], default='created', max_length=20)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('authority', models.CharField(blank=True, db_index=True, max_length=100)),
                ('ref_id', models.CharField(blank=True, max_length=100)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('callback_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests', to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Request',
                'verbose_name_plural': 'Payment Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteCommissionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='درصد کمیسیون سایت از هر سفارش (مثلاً 10.00 = ۱۰٪)', max_digits=5)),
                ('min_commission', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='حداقل مبلغ کمیسیون (تومان)', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commission Setting',
                'verbose_name_plural': 'Commission Settings',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('frozen_balance', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('withdrawable_balance', models.DecimalField(decimal_places=0, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('deposit', 'شارژ کیف\u200cپول'), ('escrow_hold', 'بلوکه برای سفارش'), ('escrow_release', 'آزاد از escrow (لغو)'), ('payment', 'پرداخت سفارش'), ('commission', 'کمیسیون سایت'), ('editor_earning', 'درآمد ادیتور'), ('withdrawal', 'برداشت ادیتور'), ('refund', 'استرداد وجه'), ('admin_adjustment', 'تعدیل ادمین')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('success', 'موفق'), ('failed', 'ناموفق'), ('reversed', 'برگشت خورده')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14)),
                ('balance_before', models.DecimalField(decimal_places=0, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=0, max_digits=14)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='orders.order')),
                ('payment_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.paymentrequest')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('paid', 'پرداخت شده')], default='pending', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('card_number', models.CharField(blank=True, max_length=20)),
                ('iban', models.CharField(blank=True, max_length=30)),
                ('account_holder_name', models.CharField(blank=True, max_length=150)),
                ('editor_note', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_withdraw_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdraw Request',
                'verbose_name_plural': 'Withdraw Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
