# Generated by Django 6.0.6 on 2026-07-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_refund_refundevidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tx_type',
            field=models.CharField(choices=[('deposit', 'شارژ کیف\u200cپول'), ('escrow_hold', 'بلوکه برای سفارش'), ('escrow_release', 'آزاد از escrow (لغو)'), ('payment', 'پرداخت سفارش'), ('commission', 'کمیسیون سایت'), ('editor_earning', 'درآمد ادیتور'), ('withdrawal', 'برداشت ادیتور'), ('refund', 'استرداد وجه'), ('admin_adjustment', 'تعدیل ادمین'), ('penalty', 'جریمه SLA')], max_length=30),
        ),
    ]
